### ISSUE TITLE
你的主板有CFG-lock解锁了吗？

### ISSUE THREAD

**Issue by xzq2325** [conversun/Z390i-PRO-WIFI-OpenCore#2]
我也是技嘉z390i的主板，opencore引导选择安装mac时log日志显示卡在[EB|#LOG:EXITBS:START]，AppleXcpmCfgLock and AppleCpuPmCfgLock都设置成true了还是没办法继续下去。

**Comment by conversun** [comment]
需要解锁:
可以参考: https://github.com/cheneyveron/hackintosh-clover-z390-aorus-pro-wifi-9700k-rx580
z390 和 z390i 一样都是 `0x5C1`
```
设置CFG Lock：
①. 到 这里 下载modGRUBShell.efi

②. 将U盘格式化为FAT32格式，新建EFI/BOOT文件夹，然后将modGRUBShell.efi改名为BOOTX64.EFI放进去

③. 按住F12开机，选择U盘，然后输入setup_var 0x5C1 0x00即可
```

**Comment by xzq2325** [comment]
谢谢！已经解锁成功了。但是还是不行。log里面显示[EB|#LOG:EXITBS:START]，
屏幕上显示
IOUSBHostInterface（0x1000000333）:matching deferred by IOUSBHostHIDDevice
USB Keyboard(0x10000033e): matching deferred by IOUSBHostHIDDevice
没有解锁之前也是显示这样的，因为日志的显示，我以为是CFG Lock的问题。现在想来可能是ACPI这里的问题。得再研究研究了。

**Comment by conversun** [comment]
那就得检查 Bios 设置了, 还是上面的链接, 比如 `XHCI Hand-off`

**Comment by xzq2325** [comment]
今天用最新的opencore重新制作了一遍，install mac 选择了之后跑完所有命令之后黑屏了。正在查bios设置了。

**Comment by xzq2325** [comment]
已经装上最新的系统了，bios上改了一些，关键的应该是添加agdpmod=pikera到启动参数。我用的是 rx 5500xt的显卡
