### ISSUE TITLE
[question] does onbord bluetooth work?

### ISSUE THREAD

**Issue by lanx-x** [conversun/Z390i-PRO-WIFI-OpenCore#4]

**Comment by Bombadaa** [comment]
Yes

**Comment by mistercorea** [comment]
What... No... you need to replace it with an apple compatible wifi card.

**Comment by Bombadaa** [comment]
Or you use the BlueToolFixup.kext

**Comment by conversun** [comment]
Recommend you to replace the Broadcom network card
