### ISSUE TITLE
freeze during boot

### ISSUE THREAD

**Issue by YaPaY** [conversun/Z390i-PRO-WIFI-OpenCore#5]
any comment?

![resim](https://user-images.githubusercontent.com/705923/126047549-b8d404b4-d638-42c9-b623-64dcdf91e4fc.png)

**Comment by YaPaY** [comment]
I found the problem CFGLock was enable. I changed the disable now I can continue but thi stime I am stuck at IOTimeSyncLocalClockport::handleGeneralnotification line.

**Comment by mistercorea** [comment]
https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/

well try it now it seems like everything works.

**Comment by conversun** [comment]
Upgrading the latest BIOS can directly turn off CFG

**Comment by mistercorea** [comment]
BTW @YaPaY I had a similar issue and it went away when I switched false-> true
```
<key>AppleXcpmCfgLock</key>
<true/>
```

That seems to resolve that issue for me.
